# -*- coding: utf-8 -*-
"""Supply_chain_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wUNSn6BD5d90H0Z35y9vrUZ1Bs2BHfUp
"""

#Import lib
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

#Load dataset
orders = pd.read_csv('orders.csv')
items = pd.read_csv('order_items.csv')
products = pd.read_csv('products.csv')

orders = pd.read_csv('orders.csv')
items = pd.read_csv('order_items.csv')
products = pd.read_csv('products.csv')

#Dataset Merge
df = orders.merge(
    items,
    on='order_id'
)
df = df.merge(
    products,
    on='product_id'
)

#Data Understanding
# Shape
orders.shape
items.shape
products.shape

# Info
orders.info()

items.info()

products.info()

#describe
orders.describe()

items.describe()

products.describe()

#Data handling- Check dublicate value
orders.duplicated().sum()

items.duplicated().sum()

products.duplicated().sum()

#check missing value
orders.isnull().sum()

items.isnull().sum()

products.isnull().sum()

#Remove rows with missing values and Save cleaned data permanently
orders = orders.dropna()  # Remove rows with missing values
orders.to_csv("orders_cleaned.csv", index=False)  # Save cleaned data permanently

products = products.dropna()
products.to_csv("products_cleaned.csv", index=False)

orders.isnull().sum()

products.isnull().sum()

#Exploratory Data Analysis (EDA)

# Qu:1 - Which product categories generate the highest number of returns?

# Filter returned/cancelled orders
returns = df[df['order_status'] == 'canceled']

# Get top returned categories
top_returns = returns['product_category_name'].value_counts().head(10)

# Plot
plt.figure(figsize=(12,6))
sns.countplot(
    data=returns,
    y='product_category_name',
    order=top_returns.index
)

plt.title('Top 10 Product Categories by Returns')
plt.xlabel('Number of Returns')
plt.ylabel('Product Category')
plt.show()

#Qu:2 - Which warehouses experience the longest delays? Metric:Delivery_Time = Delivery_Date - Purchase_Date


df['order_purchase_timestamp'] = pd.to_datetime(df['order_purchase_timestamp'])
df['order_delivered_customer_date'] = pd.to_datetime(df['order_delivered_customer_date'])

df['Delivery_Time'] = (
    df['order_delivered_customer_date'] -
    df['order_purchase_timestamp']
).dt.days

seller_delays = (
    df.groupby('seller_id')['Delivery_Time']
      .mean()
      .sort_values(ascending=False)
      .head(10)
)

plt.figure(figsize=(10,6))
sns.barplot(x=seller_delays.values, y=seller_delays.index)
plt.title('Top 10 Sellers with Longest Delivery Delays')
plt.xlabel('Average Delivery Time (Days)')
plt.ylabel('Seller ID')
plt.show()

#Qu:3 - Which months have the highest return volumes?

# Filter returned/cancelled orders
returns = df[df['order_status'] == 'canceled'].copy()

# Extract month
returns['Month'] = pd.to_datetime(
    returns['order_purchase_timestamp']
).dt.month_name()

# Count returns per month
monthly_returns = returns['Month'].value_counts().reindex([
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December'
]).fillna(0)

# Plot Monthly Trend Analysis
plt.figure(figsize=(12, 6))
sns.lineplot(x=monthly_returns.index, y=monthly_returns.values, marker='o')

plt.title('Monthly Return Volume Trend')
plt.xlabel('Month')
plt.ylabel('Number of Returns')
plt.xticks(rotation=45)
plt.show()

#Qu:4 - Does freight cost influence returns? Create: Scatter Plot

# Create return flag
df['Returned'] = (df['order_status'] == 'canceled').astype(int)

# Scatter Plot: Freight Cost vs Returns
plt.figure(figsize=(10,6))
sns.scatterplot(
    data=df,
    x='freight_value',
    y='Returned',
    alpha=0.5
)

plt.title('Does Freight Cost Influence Returns?')
plt.xlabel('Freight Cost')
plt.ylabel('Return (1 = Returned, 0 = Not Returned)')
plt.show()

# Basic - Histogram

df['Delivery_Time'] = (
    pd.to_datetime(df['order_delivered_customer_date']) -
    pd.to_datetime(df['order_purchase_timestamp'])
).dt.days

plt.figure(figsize=(10,6))
sns.histplot(df['Delivery_Time'], bins=30, kde=True)

plt.title('Distribution of Delivery Time')
plt.xlabel('Delivery Time (Days)')
plt.ylabel('Frequency')
plt.show()

# Basic - Bar chat
top_categories = df['product_category_name'].value_counts().head(10)

plt.figure(figsize=(12,6))
sns.barplot(x=top_categories.values, y=top_categories.index)

plt.title('Top 10 Product Categories by Orders')
plt.xlabel('Number of Orders')
plt.ylabel('Product Category')
plt.show()

#Basic - Pie Chart

top_categories = df['product_category_name'].value_counts().head(5)

plt.figure(figsize=(8,8))
plt.pie(
    top_categories.values,
    labels=top_categories.index,
    autopct='%1.1f%%'
)

plt.title('Order Distribution by Product Category')
plt.show()

#Intermediate - Box Plot

df['Delivery_Time'] = (
    pd.to_datetime(df['order_delivered_customer_date']) -
    pd.to_datetime(df['order_purchase_timestamp'])
).dt.days

plt.figure(figsize=(10,6))
sns.boxplot(x=df['Delivery_Time'])

plt.title('Box Plot of Delivery Time')
plt.xlabel('Delivery Time (Days)')
plt.show()

#Intermediate - Violin Plot

df['Delivery_Time'] = (
    pd.to_datetime(df['order_delivered_customer_date']) -
    pd.to_datetime(df['order_purchase_timestamp'])
).dt.days

plt.figure(figsize=(10,6))
sns.violinplot(x=df['Delivery_Time'])

plt.title('Violin Plot of Delivery Time')
plt.xlabel('Delivery Time (Days)')
plt.show()

#Intermediate - Heatmap

df['Delivery_Time'] = (
    pd.to_datetime(df['order_delivered_customer_date']) -
    pd.to_datetime(df['order_purchase_timestamp'])
).dt.days

plt.figure(figsize=(8,6))

sns.heatmap(
    df[['price', 'freight_value', 'Delivery_Time']].corr(),
    annot=True,
    cmap='coolwarm'
)

plt.title('Correlation Heatmap')
plt.show()

import os

folders = [
    "Ecommerce_SupplyChain_Project/data",
    "Ecommerce_SupplyChain_Project/notebooks",
    "Ecommerce_SupplyChain_Project/scripts",
    "Ecommerce_SupplyChain_Project/outputs",
    "Ecommerce_SupplyChain_Project/visualizations",
    "Ecommerce_SupplyChain_Project/presentation",
    "Ecommerce_SupplyChain_Project/ieee_report"
]

for folder in folders:
    os.makedirs(folder, exist_ok=True)

open("Ecommerce_SupplyChain_Project/README.md", "w").close()

!zip -r Ecommerce_SupplyChain_Project.zip Ecommerce_SupplyChain_Project

from google.colab import files

files.download('Ecommerce_SupplyChain_Project.zip')

